### ISSUE TITLE
Arkivmeldingen må støtte fødsels- og organisasjonsnummer

### ISSUE THREAD

**Issue by sturtzel** [difi/move-messagetypes#1]
P.t. er innholdet lik Noark 5.5 med få avvik.

Noark 5.5 har mangler vs. BEST/EDU, GeoIntegrasjon og Noark 5 tjenestesnitt som alle er laget med tanke på utveksling av informasjon og ikke kun avlevering.

Det er mulig at Noark 5 tjenestesnitt inneholder for mye, men strukturen der har med viktige felt. Den skiller på personer og organisasjoner og den skille på tekstlige kodebeskrivelser (ref. Noark 5) og korte koder:
https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/tree/master/xsd

**Comment by JanIvarMoldekleiv** [comment]
Arkivmelding støtter nå fødsels og organisasjonsnummer etter modell fra noark5-tjenestegrensesnitt. Jeg lukker dette punktet, og foreslår at bruk av koder diskuteres i eget issue.
